#!/usr/bin/env python
import argparse, distutils.spawn, os, sys, subprocess, tempfile, time
import boto3

ec2 = boto3.resource('ec2')

def print_instance(instance):
    print instance.id, instance.state["Name"], instance.public_ip_address,\
        instance.instance_type, tags(instance.tags)

def wait_run(instance):
    instance.wait_until_running(Filters=[{
        'Name': 'instance-id',
        'Values': [instance.instance_id],
    }])
    print "Sleeping longer, to allow boot"
    time.sleep(10)
    return ec2.Instance(instance.id)

def wait_stop(instance):
    instance.wait_until_stopped(Filters=[{
        'Name': 'instance-id',
        'Values': [instance.instance_id],
    }])
    return ec2.Instance(instance.id)

def get_by_name(name):
    return ec2.instances.filter(Filters=[{'Name': 'tag:Name',
                                          'Values': [name]}])

found = False
for instance in get_by_name("gen-small"):
    if instance.state["Name"] == 'terminated':
        print "T", instance.id, instance.instance_type
    if instance.state["Name"] == 'stopping':
        print instance.id, instance.instance_type, "is stopping"
    if instance.state["Name"] == 'stopped':
        print "Stopped", instance.id, instance.instance_type
    if instance.state["Name"] == 'pending':
        print "N", instance.id, instance.instance_type
    if instance.state["Name"] == 'running':
        print "R", instance.id, instance.instance_type
        instance.stop()
    found = True

